apiVersion: v1
kind: Service
metadata:
  labels:
    role: locust-master
  name: locust-external
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: webx
    nodePort: 31234
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    role: locust-master
  sessionAffinity: None
  type: NodePort
